version: 0.2
phases:
  install:
    commands:
      - echo "Checking available .NET versions..."
      - ls /usr/share/dotnet/sdk/
      - dotnet --list-sdks
  build:
    commands:
      - echo "Build phase"